export const NORMAL_ACCOUNT_WELCOME_BONUS_CENT = 1000;

export const NORMAL_ACCOUNT_MIN_BALANCE_CENT = -50000;
export const SAVINGS_ACCOUNT_MIN_BALANCE_CENT = 0;

export const ACCOUNT_NUMBER_FORMAT = /^\d{3}-\d{7}-\d{2}$/;
